import { GoalNode, UserMetrics } from "@/types";

export const INITIAL_METRICS: UserMetrics = {
    momentum: 85,
    streak: 12,
    lastActive: new Date(),
};

export const INITIAL_GOALS: GoalNode[] = [
    {
        id: "g-1",
        title: "Build Personal Goal",
        description: "The ultimate productivity tool for high performers",
        weight: 100,
        progress: 30,
        status: "in-progress",
        createdAt: new Date(),
        updatedAt: new Date(),
        deadline: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
        isExpanded: true,
        isFocus: false,
        children: [
            {
                id: "g-1-1",
                parentId: "g-1",
                title: "Phase 1: MVP Frontend",
                description: "Build the visual core using Next.js and Shadcn",
                weight: 40,
                progress: 30,
                status: "in-progress",
                createdAt: new Date(),
                updatedAt: new Date(),
                isExpanded: true,
                isFocus: false,
                children: [
                    {
                        id: "g-1-1-1",
                        parentId: "g-1-1",
                        title: "Setup Project",
                        weight: 20,
                        progress: 100,
                        status: "done",
                        createdAt: new Date(),
                        updatedAt: new Date(),
                        deadline: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
                        isFocus: true, // Selected for Warrior Mode
                        children: [],
                    },
                    {
                        id: "g-1-1-2",
                        parentId: "g-1-1",
                        title: "Implement Goal Tree",
                        weight: 50,
                        progress: 0,
                        status: "todo",
                        createdAt: new Date(),
                        updatedAt: new Date(),
                        isFocus: false,
                        children: [],
                    },
                    {
                        id: "g-1-1-3",
                        parentId: "g-1-1",
                        title: "Design Warrior Mode",
                        weight: 30,
                        progress: 0,
                        status: "todo",
                        createdAt: new Date(),
                        updatedAt: new Date(),
                        isFocus: false,
                        children: [],
                    },
                ],
            },
            {
                id: "g-1-2",
                parentId: "g-1",
                title: "Phase 2: Backend Engine",
                description: "Golang logic for recursive calculations",
                weight: 60,
                progress: 0,
                status: "todo",
                createdAt: new Date(),
                updatedAt: new Date(),
                isExpanded: false,
                isFocus: false,
                children: [],
            },
        ],
    },
    {
        id: "g-2",
        title: "Master Guitar",
        description: "Learn to play like a pro",
        weight: 50,
        progress: 0,
        status: "todo",
        createdAt: new Date(),
        updatedAt: new Date(),
        deadline: new Date(new Date().setMonth(new Date().getMonth() + 3)).toISOString(),
        isExpanded: false,
        isFocus: false,
        children: [
            {
                id: "g-2-1",
                parentId: "g-2",
                title: "Learn Basic Chords",
                weight: 50,
                progress: 0,
                status: "todo",
                createdAt: new Date(),
                updatedAt: new Date(),
                deadline: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
                isFocus: false,
                children: [],
            },
        ],
    },
];
